project_id = "bhepkvspmzbmdkeodvdd"

[functions.chat-ai]
verify_jwt = false

[functions.analyze-image]
verify_jwt = false

[functions.stripe-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
